
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/building
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        form_sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api-docs