
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver


  #  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/buildings
#    username: postgres
#    password: root123

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        form_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

server:
  port: 8080

springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api/docs


path:
  request: http:/
  api: /localhost:8080
  file-path: /uploads/building
  url-path: /api/v1/

