
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/building
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        form_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

server:
  port: 8080

springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api-docs

path:
  request: http:/
  api: /localhost:8080
  filePath: /uploads/building
  urlPath: /api/v1/

