



spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: pa
#    driverClassName: org.h2.Driver

  mvc:
    hiddenmethod:
      filter:
        enabled: true


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

        form_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

server:
  port: 9091

springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api/docs


path:
  request: http:/
#  api: /54.242.152.78:9091
  api: /172.105.103.209:9091
  file-path: /uploads/building
  url-path: /api/v1/

